services:
  api:
    build: .
    container_name: raagsetu-backend
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - .:/usr/src/app:cached
      - /usr/src/app/node_modules
    environment:
      - REDIS_URL=redis://redis:6379
      - PORT=3000
    command: sh -c "yt-dlp -U && npm start"
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: raagsetu-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  redis_data:
